[build]
builder = "nixpacks"

[deploy]
startCommand = "node server/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
LOG_LEVEL = "error"
TRANSCRIPTION_SERVICE_URL = "${{RAILWAY_STATIC_URL}}"
PORT = "${{PORT}}"